### ISSUE TITLE
Both context and applicationId must be non-null

### ISSUE THREAD

**Issue by duataud** [spencercarli/react-native-meteor-accounts#4]
I'm getting this from logcat with a fresh clone of " RNFacebookExample"
My facebook_app_id and meta-data  tag are in place and still crashing even adding FacebookActivity , Thanks!!

"FacebookActivity is not declared in the AndroidManifest.xml, please add com.facebook.FacebookActivity to your AndroidManifest.xml file."

"FATAL EXCEPTION: main
E/AndroidRuntime(14476): java.lang.RuntimeException: Unable to resume activity {com.rnfacebookexample/com.rnfacebookexample.MainActivity}: java.lang.IllegalArgumentException: Both context and applicationId must be non-null"

**Comment by spencercarli** [comment]
Did you change your app id here? https://github.com/spencercarli/react-native-meteor-accounts/blob/master/RNFacebookExample/android/app/src/main/res/values/strings.xml#L4

Seems like this is a similar problem to this http://stackoverflow.com/a/19922906/2296215

**Comment by duataud** [comment]
I clean my project and it worked, sorry and thanks!
